# Generated by Django 4.0.4 on 2022-04-21 16:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('otherpages', '0003_rename_policy_policypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policypage',
            name='policy_body',
            field=wagtail.core.fields.StreamField([('policy_body', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
