# Generated by Django 4.0.4 on 2022-04-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('business', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
