# Generated by Django 4.0.4 on 2022-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
