# Generated by Django 4.0.4 on 2022-04-20 20:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_articlecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
