# Generated by Django 4.0.4 on 2022-04-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_articlecategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['title'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='name',
            new_name='title',
        ),
    ]
