# Generated by Django 4.0.4 on 2022-04-20 22:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_articletagpage_articledetailpage_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='content',
            field=ckeditor.fields.RichTextField(default='something'),
            preserve_default=False,
        ),
    ]
