# Generated by Django 4.0.4 on 2022-04-20 22:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_articledetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailpage',
            name='sample_answer',
            field=wagtail.core.fields.StreamField([('sample_answer', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
