# Generated by Django 4.0.4 on 2022-04-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('resources', '0010_remove_articledetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailpage',
            name='question_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
