# Generated by Django 4.0.4 on 2022-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemangersetting',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
