# Generated by Django 4.0.4 on 2022-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0002_sitemangersetting_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemangersetting',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
