# Generated by Django 4.0.4 on 2022-04-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='here we are', max_length=43),
            preserve_default=False,
        ),
    ]
