# Generated by Django 4.0.4 on 2022-04-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
