# Generated by Django 4.0.4 on 2022-04-17 19:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_about_content',
            field=wagtail.core.fields.StreamField([('About_section_content', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
