# Generated by Django 4.0.4 on 2022-04-17 20:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_section_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section_about',
            field=wagtail.core.fields.StreamField([('section_headings', wagtail.core.blocks.StructBlock([('eyebrow', wagtail.core.blocks.CharBlock(help_text='Section eyebrow', required=False)), ('headline', wagtail.core.blocks.CharBlock(help_text='Section headline', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False))], null=True))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_about_content',
            field=wagtail.core.fields.StreamField([('section_content', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
