# Generated by Django 4.0.4 on 2022-04-17 20:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_section_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='core_features',
            field=wagtail.core.fields.StreamField([('section_core_section', wagtail.core.blocks.StructBlock([('eyebrow', wagtail.core.blocks.CharBlock(help_text='Section eyebrow', required=False)), ('headline', wagtail.core.blocks.CharBlock(help_text='Section headline', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False))], null=True))], null=True),
        ),
    ]
