# Generated by Django 4.0.4 on 2022-04-18 05:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_core_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='core_features_cards',
            field=wagtail.core.fields.StreamField([('features_cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('fontawesome', wagtail.core.blocks.CharBlock(help_text='Add Font awesome Markup reference', required=False)), ('headline', wagtail.core.blocks.CharBlock(help_text='Card headline', required=False)), ('description', wagtail.core.blocks.TextBlock(help_text='Section headline', required=False))])))]))], null=True),
        ),
    ]
