# Generated by Django 4.0.4 on 2022-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_core_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_bullet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
