# Generated by Django 4.0.4 on 2022-04-18 10:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_about_bullet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_bullet',
            field=wagtail.core.fields.StreamField([('about_bullet', wagtail.core.blocks.CharBlock(required=False))], null=True),
        ),
    ]
