# Generated by Django 4.0.4 on 2022-04-18 10:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_alter_homepage_about_bullet'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_about_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_about_content',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False))], null=True),
        ),
    ]
