# Generated by Django 4.0.4 on 2022-04-18 19:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homepage_section_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='core_features',
            field=wagtail.core.fields.StreamField([('section_core_section', wagtail.core.blocks.StructBlock([('eyebrow', wagtail.core.blocks.CharBlock(help_text='Section eyebrow', required=False)), ('headline', wagtail.core.blocks.CharBlock(help_text='Section headline', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False))]))], null=True),
        ),
    ]
