# Generated by Django 4.0.4 on 2022-04-18 19:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_core_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='citation_hub',
            field=wagtail.core.fields.StreamField([('citation_section', wagtail.core.blocks.StructBlock([('eyebrow', wagtail.core.blocks.CharBlock(help_text='Section eyebrow', required=False)), ('headline', wagtail.core.blocks.CharBlock(help_text='Section headline', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False))]))], null=True),
        ),
    ]
