# Generated by Django 4.0.4 on 2022-04-20 07:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_datasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='right_points',
            field=wagtail.core.fields.StreamField([('right_points', wagtail.core.blocks.CharBlock(required=False))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='datasection',
            field=wagtail.core.fields.StreamField([('datasection_headings', wagtail.core.blocks.StructBlock([('eyebrow', wagtail.core.blocks.CharBlock(help_text='Section eyebrow', required=False)), ('headline', wagtail.core.blocks.CharBlock(help_text='Section headline', required=False)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Section description', required=False))]))], null=True),
        ),
    ]
