# Generated by Django 4.0.4 on 2022-04-20 07:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_homepage_right_points_alter_homepage_datasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='data_counter',
            field=wagtail.core.fields.StreamField([('data_counter', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('max_count', wagtail.core.blocks.CharBlock(help_text='Data Max number count', required=False)), ('item_text', wagtail.core.blocks.CharBlock(help_text='Data item text below the counting numbers', required=False))])))]))], null=True),
        ),
    ]
