# Generated by Django 4.0.4 on 2022-04-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homepage_data_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='data_counter',
        ),
    ]
