# Generated by Django 4.0.4 on 2022-04-20 08:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_data_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='right_points',
        ),
        migrations.AddField(
            model_name='homepage',
            name='data_bullets',
            field=wagtail.core.fields.StreamField([('data_bullets', wagtail.core.blocks.CharBlock(required=False))], null=True),
        ),
    ]
