# Generated by Django 4.0.4 on 2022-04-20 17:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_homepage_right_points_homepage_data_bullets'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='jumbo_area',
            field=wagtail.core.fields.StreamField([('About_section', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('cardicon', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.CharBlock(help_text='Card headline', required=False)), ('description', wagtail.core.blocks.TextBlock(help_text='Section headline', required=False))])))], null=True))], null=True),
        ),
    ]
